api/urls.py
from django.conf.urls import url

from api import views

app_name = 'api'
urlpatterns = [
    url(r'^emails/$', views.EmailBase.as_view()),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/$', views.EmailDetail.as_view(), name='email_details'),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/header/$', views.EmailHeader.as_view()),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/bodies/$', views.EmailBodies.as_view()),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/attachments/$', views.EmailAttachments.as_view()),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/analysis/$', views.EmailAnalysis.as_view()),
    url(r'^headers/(?P<pk>[0-9a-f]{64})/$', views.HeaderDetail.as_view()),
    url(r'^headers/(?P<pk>[0-9a-f]{64})/emails/$', views.HeaderEmails.as_view()),
    url(r'^headers/(?P<pk>[0-9a-f]{64})/vote/$', views.HeaderVotes.as_view()),
    url(r'^bodies/(?P<pk>[0-9a-f]{64})/$', views.BodyDetail.as_view()),
    url(r'^bodies/(?P<pk>[0-9a-f]{64})/emails/$', views.BodyEmails.as_view()),
    url(r'^attachments/(?P<pk>[0-9a-f]{64})/$', views.AttachmentDetail.as_view()),
    url(r'^attachments/(?P<pk>[0-9a-f]{64})/emails/$', views.AttachmentEmails.as_view()),
    url(r'^domains/$', views.DomainBase.as_view()),
    url(r'^emailAddresses/$', views.EmailAddressBase.as_view()),
    url(r'^ipAddresses/$', views.IpAddressBase.as_view()),
    url(r'^urls/$', views.UrlBase.as_view()),
]

details/urls.py
from django.conf.urls import url

from . import views

app_name = 'details'
urlpatterns = [
    url(r'^$', views.redirect_to_homepage),
    url(r'^(?P<pk>[0-9a-f]{64})/?$', views.EmailDetailView.as_view(), name='details'),
    url(r'^(?P<pk>[0-9a-f]{64})/feedback/?$', views.EmailFeedbackView.as_view(), name='feedback'),
    url(r'^(?P<pk>[0-9a-f]{64})/redaction/?$', views.EmailRedactionView.as_view(), name='redaction'),
    url(r'^(?P<pk>[0-9a-f]{64})/reanalyze/?$', views.reanalyze_email, name='reanalyze'),
]

search/urls.py
from django.conf.urls import url

from . import views

app_name = 'search'
urlpatterns = [url(r'^$', views.IndexSearchView.as_view(), name='index')]

search/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re

from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib import messages

from db.models import Email
from .search_mappings import (
    header_search_mappings,
    body_search_mappings,
    network_data_search_mappings,
    attachment_search_mappings,
)
from totalemail.settings import _validate_search_query, MAX_RESULTS
from utility import utility

SEARCH_PATTERN_REGEX = '(\w*\(.*?\))'


def _add_email_results(existing_email_list, new_emails, search_query):
    unique_new_emails = []
    existing_email_ids = [email['email'].id for email in existing_email_list]

    for email in new_emails:
        if email.id not in existing_email_ids:
            unique_new_emails.append(
                {'email': email, 'search_query': search_query, 'score': utility.email_score_calculate(email)}
            )
            existing_email_ids.append(email.id)

    return unique_new_emails


class IndexSearchView(TemplateView):
    """Base search page."""

    def get(self, request):
        """Handle get requests."""
        template_name = "search/search_index.html"
        all_email_objects = Email.objects.all()
        total_email_count = len(all_email_objects)
        query_string = request.GET.get("q")
        original_query_string = query_string
        if query_string:
            if len(query_string) < 3:
                messages.info(request, 'Please enter a search term that is 3 characters or longer')
                return render(request, template_name, {'q': query_string})

            emails = list()

            _validate_search_query(query_string)

            # get the custom search queries used in the search
            queries_with_custom_functions = re.findall(SEARCH_PATTERN_REGEX, query_string)

            for query in queries_with_custom_functions:
                query = query.strip()

                # find the function of the custom query
                function = query.split('(')[0]
                # find the search value of the custom query (we are joining on '(' in case the query has a '(' in it)
                search = '('.join(query.split('(')[1:]).lower().strip(')')
                function_found = False

                if function in header_search_mappings:
                    function_found = True
                    results = [
                        email
                        for email in all_email_objects.order_by('-first_seen')
                        if email.header.header_value_contains(header_search_mappings[function])
                    ]
                    emails.extend(_add_email_results(emails, results, query))
                elif function in body_search_mappings:
                    function_found = True
                    if function == 'bod':
                        results = Email.objects.filter(bodies__full_text__icontains=search).order_by('-first_seen')
                        emails.extend(_add_email_results(emails, results, query))
                elif function in network_data_search_mappings:
                    function_found = True
                    # find emails with the domain
                    if function == 'dom':
                        results = Email.objects.filter(header__host__host_name__icontains=search).order_by(
                            '-first_seen'
                        )
                        emails.extend(_add_email_results(emails, results, query))
                        results = Email.objects.filter(bodies__host__host_name__icontains=search).order_by(
                            '-first_seen'
                        )
                    # find emails with the domain in the header
                    elif function == 'domh':
                        results = Email.objects.filter(header__host__host_name__icontains=search).order_by(
                            '-first_seen'
                        )
                    # find emails with the domain in the body
                    elif function == 'domb':
                        results = Email.objects.filter(bodies__host__host_name__icontains=search).order_by(
                            '-first_seen'
                        )
                    emails.extend(_add_email_results(emails, results, query))
                elif function in attachment_search_mappings:
                    function_found = True
                    if function == 'hasAttachment':
                        results = Email.objects.filter(attachments__isnull=False).order_by('-first_seen')
                    emails.extend(_add_email_results(emails, results, query))

                if function_found:
                    # remove the query from the full search query
                    query_string = query_string.replace(query, '')

            query_string = query_string.strip()
            if query_string:
                # search for the remaining query (which has the queries with custom functions removed)
                results = Email.objects.filter(full_text__icontains=query_string).order_by('-first_seen')
                emails.extend(_add_email_results(emails, results, query_string))

            return render(
                request,
                template_name,
                {
                    "max_results": MAX_RESULTS,
                    "total_result_count": len(emails),
                    "results": emails[:MAX_RESULTS],
                    "q": original_query_string,
                    "total_email_count": total_email_count,
                },
            )
        else:
            return render(request, template_name, {"total_email_count": total_email_count})

templates/search/search_index.html
{% extends 'totalemail/base.html' %}

{% block title %}Search: {{ q|truncatechars:42 }}{% endblock %}

{% block content %}

<!-- TODO: make the space from the top dynamic based on the size of the screen... also do this on the importer-index and other importer page. -->
<br>

<div class="text-center row">
    <h1>Search the Emails</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            {% autoescape off %}
                <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
                <br>
            {% endautoescape %}
        {% endfor %}
        <br>
    {% endif %}

    <form action="{% url 'search:index' %}" method="get">
        <input id="searchBox" type="text" placeholder="Search for something here..." name="q" value="{{ q }}">
        <p><i>Searching {{ total_email_count }} email{{ total_email_count|pluralize }}</i></p>
        <p>
            <input class="hollow medium button success" type="submit" value="Search">
            {% if q != None %}
                <a class="hollow medium button secondary" href="{% url 'search:index' %}">Clear</a>
            {% endif %}
        </p>
        <p>
            {% if q == None %}
                Not sure what to search for? <a href="{% url 'search:index' %}?q=subject">View recent emails</a>.
            {% endif %}
        </p>
    </form>

    <br>

    <div class="large-6 medium-9 small-12 float-center">
        {% if results %}
            {% if total_result_count > max_results %}
                <!-- TODO: Add a tooltip to this message explaining why we are limiting the results -->
                Showing {{ results|length }} of {{ total_result_count }} emails matching "<i>{{ q }}</i>":
            {% else %}
                Found {{ results|length }} email{{ results|length|pluralize }} matching "<i>{{ q }}</i>":
            {% endif %}
            <br><br>
            <ul style="list-style: none;">
            {% for email in results %}
                <li style="margin-bottom: -1em;" class="text-left" title="Email score: {{ email.score }}">
                    {% if email.score > 0.666 %}
                        <span style="color: #E64A48; font-size: 2em; vertical-align: middle;">•</span>
                    {% elif email.score < 0.334 %}
                        <span style="color: #6FEF87; font-size: 2em; vertical-align: middle;">•</span>
                    {% else %}
                        <span style="color: #F1D86C; font-size: 2em; vertical-align: middle;">•</span>
                    {% endif %}
                    <a href="{% url 'details:details' email.email.id %}" target="_blank">{{ email.email.header.subject }}</a> (<i>{{ email.search_query }}</i>)
                </li>
            {% endfor %}
            </ul>
        {% else %}
            {% if q != None %}
                No results found for "<i>{{ q }}</i>". <a href="{% url 'search:index' %}?q=subject">View recent emails</a>.
            {% endif %}
            <br>
        {% endif %}
    </div>

    <br><hr><br>

    <div class="large-8 medium-9 float-center">
        <h4>Search Functions</h4>
        <p>Every search can be wrapped in one of the functions below to specify where you would like to find a specific query:</p>

        <ul style="list-style: none;">
            <li>
                <b>sub</b>({subject}) - Search for emails with the given subject - examples: <a href="{% url 'search:index' %}?q=sub(spam)">sub(spam)</a>, <a href="{% url 'search:index' %}?q=sub(talk to)">sub(talk to)</a>
            </li>
            <li>
                <b>to</b>({recipient address/name}) - Search for emails with the given recipient address - <a href="{% url 'search:index' %}?q=to(redacted)">to(redacted)</a>
            </li>
            <li>
                <b>from</b>({sending address/name}) - Search for emails with the given sending address - <a href="{% url 'search:index' %}?q=from(tulip.ocn.ne.jp)">from(tulip.ocn.ne.jp)</a>, <a href="{% url 'search:index' %}?q=from(Fedex.shipping@ikexpress.com)">from(Fedex.shipping@ikexpress.com)</a>, <a href="{% url 'search:index' %}?q=from(Thank You)">from(Thank You)</a>
            </li>
            <li>
                <b>bod</b>({text}) - Search for emails with the given text in the body - <a href="{% url 'search:index' %}?q=bod(money)">bod(money)</a>, <a href="{% url 'search:index' %}?q=bod(good day)">bod(good day)</a>
            </li>
            <li>
                <b>dom</b>({domain name}) - Search for emails with the given domain name - <a href="{% url 'search:index' %}?q=dom(tulip.ocn.ne.jp)">dom(tulip.ocn.ne.jp)</a>
            </li>
            <li>
                <b>domh</b>({domain name}) - Search for emails with the given domain name in the header - <a href="{% url 'search:index' %}?q=domh(tulip.ocn.ne.jp)">domh(tulip.ocn.ne.jp)</a>
            </li>
            <li>
                <b>domb</b>({domain name}) - Search for emails with the given domain name in a body - <a href="{% url 'search:index' %}?q=domb(bit.ly)">domb(bit.ly)</a>
            </li>
            <li>
                <b>hasAttachment</b>() - Find emails with at least one attachment - <a href="{% url 'search:index' %}?q=hasAttachment()">hasAttachment()</a>
            </li>
        </ul>
    </div>
</div>

<script>
    window.onload = function() {
        $(document).foundation();

        window.setTimeout(function() {
            $('#searchBox').select();
        }, 100);

        // $('#searchBox').on({
        //     keyup: function(event) {
        //         var currentSearchValue = $('#searchBox').val();
        //         if (event.key === '(' && currentSearchValue.indexOf('(') === currentSearchValue.length - 1) {
        //             $('#searchBox').val(currentSearchValue + ')');
        //         }
        //     }
        // });
    }
</script>

{% endblock %}