api/urls.py
from django.conf.urls import url

from api import views

app_name = 'api'
urlpatterns = [
    url(r'^emails/$', views.EmailBase.as_view()),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/$', views.EmailDetail.as_view(), name='email_details'),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/header/$', views.EmailHeader.as_view()),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/bodies/$', views.EmailBodies.as_view()),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/attachments/$', views.EmailAttachments.as_view()),
    url(r'^emails/(?P<pk>[0-9a-f]{64})/analysis/$', views.EmailAnalysis.as_view()),
    url(r'^headers/(?P<pk>[0-9a-f]{64})/$', views.HeaderDetail.as_view()),
    url(r'^headers/(?P<pk>[0-9a-f]{64})/emails/$', views.HeaderEmails.as_view()),
    url(r'^headers/(?P<pk>[0-9a-f]{64})/vote/$', views.HeaderVotes.as_view()),
    url(r'^bodies/(?P<pk>[0-9a-f]{64})/$', views.BodyDetail.as_view()),
    url(r'^bodies/(?P<pk>[0-9a-f]{64})/emails/$', views.BodyEmails.as_view()),
    url(r'^attachments/(?P<pk>[0-9a-f]{64})/$', views.AttachmentDetail.as_view()),
    url(r'^attachments/(?P<pk>[0-9a-f]{64})/emails/$', views.AttachmentEmails.as_view()),
    url(r'^domains/$', views.DomainBase.as_view()),
    url(r'^emailAddresses/$', views.EmailAddressBase.as_view()),
    url(r'^ipAddresses/$', views.IpAddressBase.as_view()),
    url(r'^urls/$', views.UrlBase.as_view()),
]

details/urls.py
from django.conf.urls import url

from . import views

app_name = 'details'
urlpatterns = [
    url(r'^$', views.redirect_to_homepage),
    url(r'^(?P<pk>[0-9a-f]{64})/?$', views.EmailDetailView.as_view(), name='details'),
    url(r'^(?P<pk>[0-9a-f]{64})/feedback/?$', views.EmailFeedbackView.as_view(), name='feedback'),
    url(r'^(?P<pk>[0-9a-f]{64})/redaction/?$', views.EmailRedactionView.as_view(), name='redaction'),
    url(r'^(?P<pk>[0-9a-f]{64})/reanalyze/?$', views.reanalyze_email, name='reanalyze'),
]

details/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import datetime

from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from db.models import Email
import analyzer
from utility import utility
from totalemail import settings


def redirect_to_homepage(request):
    return HttpResponseRedirect('/')


class EmailDetailView(generic.DetailView):
    model = Email
    template_name = "details/email-details-base.html"

    def get_context_data(self, **kwargs):
        context = super(EmailDetailView, self).get_context_data(**kwargs)
        email_id = self.object.id

        # note: we don't need to handle cases where the given email id is invalid because this is handled by the parent class (generic.DetailView)
        email = Email.objects.get(pk=email_id)

        network_data, network_data_flat_list, network_data_overlaps, network_data_count = email.network_data()

        network_data_header_count = (
            len(network_data['header']['hosts'])
            + len(network_data['header']['ip_addresses'])
            + len(network_data['header']['email_addresses'])
        )
        network_data_body_count = (
            len(network_data['bodies']['hosts'])
            + len(network_data['bodies']['ip_addresses'])
            + len(network_data['bodies']['email_addresses'])
            + len(network_data['bodies']['urls'])
        )

        context['network_data'] = network_data
        context['network_data_flat_list'] = network_data_flat_list
        context['network_data_overlaps'] = network_data_overlaps
        context['network_data_count'] = network_data_count
        context['network_data_header_count'] = network_data_header_count
        context['network_data_body_count'] = network_data_body_count
        context['score'] = utility.email_score_calculate(email)

        try:
            # check to see if email was recently uploaded (if so, how a jgrowl letting them know they can refresh the page to view the external analyses)
            today = datetime.datetime.today()
            delta = datetime.timedelta(seconds=20)
            if (today - delta) < email.modified:
                context['new'] = True
            else:
                context['new'] = False
        except AttributeError:
            pass

        return context


def reanalyze_email(request, **kwargs):
    """Resubmit an email for analysis."""
    try:
        email = Email.objects.get(pk=kwargs['pk'])
    except ObjectDoesNotExist:
        messages.error(request, 'No email found with the ID: {}'.format(kwargs['pk']))
        return HttpResponseRedirect('/')
    else:
        analyzer.start_analysis(email, True)
        messages.info(request, 'Email submitted for reanalysis. Updated results should be posted shortly.')
        return HttpResponseRedirect(reverse('details:details', args=(kwargs['pk'],)))


class EmailFeedbackView(generic.DetailView):
    model = Email
    template_name = 'details/email-feedback.html'

    def post(self, request, **kwargs):
        """."""
        feedback_text = request.POST.get('feedback')
        email_id = kwargs['pk']

        if feedback_text:
            feedback = '{}:{}:{}'.format(
                feedback_text, email_id, settings._process_request_data(settings._get_request_data(request))
            )
            utility.create_alerta_alert('Feedback: {}'.format(feedback[:16]), 'info', feedback)
            messages.info(request, 'Thank you! Your feedback has been recorded.')
            return HttpResponseRedirect(reverse('details:details', args=(email_id,)))
        else:
            messages.error(request, 'Please provide feedback to help us improve!')
            return HttpResponseRedirect(request.path)


class EmailRedactionView(generic.DetailView):
    model = Email
    template_name = 'details/email-redaction.html'

    def post(self, request, **kwargs):
        """."""
        redaction_request_text = request.POST.get('redactionRequest')
        email_id = kwargs['pk']

        if redaction_request_text:
            redaction_request = '{}:{}:{}'.format(
                redaction_request_text, email_id, settings._process_request_data(settings._get_request_data(request))
            )
            utility.create_alerta_alert(
                'Redaction request: {}'.format(redaction_request[:16]), 'info', redaction_request
            )
            messages.info(request, 'Thank you! Your redaction request has been recorded.')
            return HttpResponseRedirect(reverse('details:details', args=(email_id,)))
        else:
            messages.error(
                request, 'Please provide some details about what you would like to be redacted from the email.'
            )
            return HttpResponseRedirect(request.path)

templates/details/details_view/analysis-details.html
<h3 id="analyses">Analyses</h3>

<ul class="vertical menu" data-accordion-menu>
    {% for analysis in email.analysis_set.all %}
        <li>
            <a href="">{{ analysis.source|title }} - <i>{{ analysis.first_seen|date:"DATE_FORMAT" }}</i></a>

            <ul class="menu vertical">
                {% for note in analysis.notes_strings %}
                    {% autoescape off %}
                        <li class="columns">{{ note }}</li>
                    {% endautoescape %}
                {% endfor %}
                <br>
            </ul>
        </li>
    {% endfor %}
    {% if email.header.subject_not_suspicious_votes %}
        <li>
            <p>
                The subject line of this email has been voted as <b>non-malicious {{ email.header.subject_not_suspicious_votes }} time{{ email.header.subject_not_suspicious_votes|pluralize }}</b>
            </p>
        </li>
    {% endif %}
    {% if email.header.subject_suspicious_votes %}
        <li>
            <p>
                The subject line of this email has been voted as <b>malicious {{ email.header.subject_suspicious_votes }} time{{ email.header.subject_suspicious_votes|pluralize }}</b>
            </p>
        </li>
    {% endif %}
</ul>

templates/details/details_view/email-attachments.html
<h3 id="attachments">Attachments</h3>

<ul class="vertical menu" data-accordion-menu>
    {% for attachment in email.attachments.all %}
        <li class="columns">
          <a href="" id="{{ attachment.id }}">{{ attachment.content_type }} ({{ attachment.filenames|join:", " }})</a>
          <ul class="menu vertical">
            <li class="columns">
              <b>MD5:</b> {{ attachment.md5 }}<br>
              <b>SHA1:</b> {{ attachment.sha1 }}<br>
              <b>SHA256:</b> {{ attachment.sha256 }}<br>
            </li>
            <li class="columns">
              <pre style="background-color: lightgrey;">{{ attachment.full_text }}</pre>
            </li>
          </ul>
        </li>
    {% endfor %}
</ul>
<br><br>

templates/details/details_view/email-body.html
<h3 id="bodies">Bodies</h3>

<ul class="vertical menu" data-accordion-menu>
    {% for body in email.bodies.all|dictsort:"first_seen" %}
        <li class="columns">
            <a href="" id="{{ body.id }}">{{ body.content_type }}</a>
            <ul class="menu vertical">
                <li class="columns">
                    <pre style="background-color: lightgrey;" id="{{ body.id }}">{{ body.full_text }}</pre>
                </li>
            </ul>
        </li>
    {% endfor %}
</ul>

templates/details/details_view/email-details.html
<div>
    <h3 id="details">Email Details</h3>

    <span title="{{ email.first_seen }}"><b>First submitted:</b> {{ email.first_seen|timesince }} ago.</span>
    <br>
    <span title="{{ email.modified }}"><b>Most recently submitted:</b> {{ email.modified|timesince }} ago.</span>
    <br>
    <b>TrendMicro Locality Sensitive Hash:</b> {{ email.tlsh_hash }} <a href="https://github.com/trendmicro/tlsh" target="_blank"><span data-tooltip aria-haspopup="true" class="has-tip" data-disable-hover="false" tabindex=1 title="The TrendMicro Locality Sensitive Hash is a fuzzy hash developed by TrendMicro. Click to learn more."><i class="fa fa-question-circle" style="color: black;"></i></span></a>
    <br>
    <b>Score:</b> {{ score|floatformat:3 }} <a href="https://blog.totalemail.io/email-scoring-0/" target="_blank"><span data-tooltip aria-haspopup="true" class="has-tip" data-disable-hover="false" tabindex=1 title="An email's score ranges from zero to one. Lower scores indicate that an email is likely benign. Higher values indicate that an email is likely malicious. Click to learn more."><i class="fa fa-question-circle" style="color: black;"></i></span></a>
</div>

<div class="text-center">
    {% if score > 0.666 %}
        {% load static %}
        <img src="{% static "tl_red.svg.png" %}" alt="There is evidence this email is MALICIOUS" title="There is evidence this email is MALICIOUS">
        <div class="clearfix"><br></div>
        <i>There is evidence this email is MALICIOUS</i> <a href="https://blog.totalemail.io/email-scoring-0/" target="_blank"><span data-tooltip aria-haspopup="true" class="has-tip" data-disable-hover="false" tabindex=1 title="An email's score ranges from zero to one. Lower scores indicate that an email is likely benign. Higher values indicate that an email is likely malicious. Click to learn more."><i class="fa fa-question-circle" style="color: black;"></i></span></a>
    {% elif score < 0.334 %}
        {% load static %}
        <img src="{% static "tl_green.svg.png" %}" alt="There is evidence this email is BENIGN" title="There is evidence this email is BENIGN">
        <div class="clearfix"><br></div>
        <i>There is evidence this email is BENIGN</i> <a href="https://blog.totalemail.io/email-scoring-0/" target="_blank"><span data-tooltip aria-haspopup="true" class="has-tip" data-disable-hover="false" tabindex=1 title="An email's score ranges from zero to one. Lower scores indicate that an email is likely benign. Higher values indicate that an email is likely malicious. Click to learn more."><i class="fa fa-question-circle" style="color: black;"></i></span></a>
    {% else %}
        {% load static %}
        <img src="{% static "tl_yellow.svg.png" %}" alt="There is evidence this email is SUSPICIOUS" title="There is evidence this email is SUSPICIOUS">
        <div class="clearfix"><br></div>
        <i>There is evidence this email is SUSPICIOUS</i> <a href="https://blog.totalemail.io/email-scoring-0/" target="_blank"><span data-tooltip aria-haspopup="true" class="has-tip" data-disable-hover="false" tabindex=1 title="An email's score ranges from zero to one. Lower scores indicate that an email is likely benign. Higher values indicate that an email is likely malicious. Click to learn more."><i class="fa fa-question-circle" style="color: black;"></i></span></a>
    {% endif %}
</div>

templates/details/details_view/email-header.html
<h3 id="header">Header</h3>

<ul>
    <pre style="background-color: lightgrey;">{{ email.header }}</pre>
</ul>

templates/details/details_view/email-summary-card.html
<div class="card">
    <div>
        <div class="card-divider">
            <b>Email Sections</b>
        </div>
        <div class="card-section">
            {% if email.header|slugify != '' %}
            <a href="#header">Header</a><br>
            {% endif %}
            {% if email.bodies.all %}
            <a href="#bodies">Bodies</a><br>
            {% endif %}
            {% if email.attachments.all %}
            <a href="#attachments">Attachments</a>
            {% endif %}
        </div>
    </div>
    <div>
        <div class="card-divider">
            <b>Email Structure</b>
        </div>
        <div class="card-section">
            {% autoescape off %}
                {{ email.structure_as_html }}
            {% endautoescape %}
        </div>
    </div>
    <div>
        {% if network_data_count != 0 or email.analysis_set.all or email.header.subject_not_suspicious_votes or email.header.subject_suspicious_votes %}
          <div class="card-divider">
              <b>Details</b>
          </div>
          <div class="card-section">
              {% if email.analysis_set.all or email.header.subject_not_suspicious_votes or email.header.subject_suspicious_votes %}
                <p><a href="#analyses">Analyses</a></p>
              {% endif %}
              {% if network_data_count != 0 %}
                <p><a href="#networkData">Network Data</a></p>
              {% endif %}
          </div>
        {% endif %}
    </div>
    <div>
        <div class="card-divider">
            <b>Actions</b>
        </div>
        <div class="card-section">
            <p><a href="{% url 'details:reanalyze' email.id %}">Resubmit for analysis</a></p>
            <p><a href="{% url 'details:feedback' email.id %}" title="Provide feedback about this email or TotalEmail as a whole">Provide feedback</a></p>
            <p><a href="{% url 'details:redaction' email.id %}" title="Request that information be removed from this email (e.g. PII or trade secrets)">Request email redaction</a></p>
        </div>
    </div>
</div>

templates/details/details_view/network-data-base.html
<h3 id="networkData">Network Data ({{ network_data_flat_list|length }})</h3>
<p><i>({{ network_data_overlaps }} overlap{{ network_data_overlaps|pluralize }} with other emails)</i></p>

{% if network_data_header_count > 0 %}
    <h4>Network data in headers ({{ network_data_header_count }}):</h4>

    {% include "details/details_view/network_data_views/header-network-data.html" %}
    <br>
{% endif %}

{% if network_data_body_count > 0 %}
    <h4>Network data in bodies ({{ network_data_body_count }}):</h4>

    {% include "details/details_view/network_data_views/bodies-network-data.html" %}
{% endif %}

<button class="button secondary" onclick="copyNetworkData()">Copy Network Data</button>

<!-- The styling on this element hides it from the screen (see the "Position Absolute and Offscreen" section here: https://snook.ca/archives/html_and_css/hiding-content-for-accessibility) -->
<textarea id="networkDataHidden" style="position: absolute; overflow: hidden; clip: rect(0 0 0 0); height: 1px; width: 1px; margin: -1px; padding: 0; border: 0;" cols="30" rows="10">{{ network_data_flat_list|join:',' }}</textarea>

<script>
    function copyNetworkData() {
        var copyText = document.getElementById("networkDataHidden");
        copyText.select();
        var copied = document.execCommand("copy");
        if (copied) {
            $.jGrowl('Network data has been copied.', {group: 'success-growl'});
        } else {
            $.jGrowl('Unable to copy network data, sorry. Try upgrading your browser or using a different browser', {group: 'failure-growl'});
        }
    }
</script>